"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestBaselineOfIOTConnectivity,
	#superclass : #PackageManifest,
	#category : #'BaselineOfIOTConnectivity-Manifest'
}

{ #category : #'code-critics' }
ManifestBaselineOfIOTConnectivity class >> ruleRBUtilityMethodsRuleV1FalsePositive [
	^ #(#(#(#RGMethodDefinition #(#BaselineOfIOTConnectivity #baseline: #false)) #'2018-11-30T11:09:05.662576+01:00') )
]
