function main(){var a=new XMLHttpRequest;a.open("GET","daten.xml",!1);a.send();xml_daten=a.responseXML;max_1=xml_daten.getElementsByTagName("interesse").length;max_2=xml_daten.getElementsByTagName("aufgabe").length;document.getElementById("side_progress_text_2").innerHTML=max_1+"";document.getElementById("side_progress_text_4").innerHTML=max_2+"";a=document.getElementById("page_0");removeClass(a,"unused");removeClass(a,"unused_bottom");setTimeout(function(){removeClass(document.getElementById("pg_0_heading"),
"unused_top")},900);setTimeout(function(){removeClass(document.getElementById("pg_0_text"),"unused_top")},1E3);setTimeout(function(){removeClass(document.getElementById("pg_0_button"),"unused_top")},1200)}
function wechsel_seite(a){var b=document.getElementById("page_"+seite);addClass(b,"unused_top");setTimeout(function(){addClass(b,"unused")},500);counter=0;seite=a;a=document.getElementById("page_"+seite);removeClass(a,"unused");removeClass(a,"unused_bottom");setTimeout(function(){removeClass(document.getElementById("pg_"+seite+"_heading"),"unused_top")},600);setTimeout(function(){removeClass(document.getElementById("pg_"+seite+"_text"),"unused_top")},700)}
function hasClass(a,b){return a.className.match(new RegExp("(\\s|^)"+b+"(\\s|$)"))}function addClass(a,b){this.hasClass(a,b)||(a.className+=" "+b)}function removeClass(a,b){hasClass(a,b)&&(a.className=a.className.replace(new RegExp("(\\s|^)"+b+"(\\s|$)")," "))}
function showNote(a,b,c,f,d){d=document.createEvent("MouseEvents");d.initEvent("click",!0,!1);document.getElementById(b).parentNode.dispatchEvent(d);var e=document.getElementById(b);removeClass(e,"unused_all");setTimeout(function(){removeClass(e,c)},10);var h=a.currentTarget,g=function(a){a=a.target;do{if(a.id==b)return!0;a=a.parentNode}while(void 0!=a);addClass(e,f);removeClass(h,"highlight");setTimeout(function(){addClass(e,"unused_all")},500);document.removeEventListener("click",g)};document.addEventListener("click",
g);a.stopPropagation()}
function beginn(a){var b=document.getElementById("page_0");addClass(b,"unused_left");setTimeout(function(){addClass(b,"unused")},800);counter=0;seite=1;var c=document.getElementById("page_1");removeClass(c,"unused");removeClass(c,"unused_bottom");setTimeout(function(){removeClass(document.getElementById("pg_1_heading"),"unused_top")},600);setTimeout(function(){removeClass(document.getElementById("pg_1_text"),"unused_top")},700);setTimeout(function(){spawn_interesse("pg_1_spawn_1")},800);setTimeout(function(){spawn_interesse("pg_1_spawn_2")},
900);setTimeout(function(){spawn_interesse("pg_1_spawn_3")},1E3);setTimeout(function(){removeClass(document.getElementById("pg_1_drop_1"),"unused_bottom")},1100);setTimeout(function(){removeClass(document.getElementById("pg_1_drop_2"),"unused_bottom")},1200);setTimeout(function(){removeClass(document.getElementById("pg_1_drop_3"),"unused_bottom")},1300);setTimeout(function(){removeClass(document.getElementById("pg_1_drop_4"),"unused_bottom")},1400);setTimeout(function(){removeClass(document.getElementById("pg_1_drop_5"),
"unused_bottom")},1500);c=document.getElementById("side_bar");setTimeout(function(){removeClass(c,"unused");removeClass(c,"unused_left")},1600);setTimeout(function(){removeClass(document.getElementById("side_text_1"),"unused_left")},2200);setTimeout(function(){removeClass(document.getElementById("side_progress_1"),"unused_left")},2300);setTimeout(function(){removeClass(document.getElementById("side_text_2"),"unused_left")},2400);setTimeout(function(){removeClass(document.getElementById("side_progress_2"),
"unused_left")},2500);setTimeout(function(){removeClass(document.getElementById("side_bottom"),"unused_bottom")},2600)}function drop_interesse(a){a.preventDefault();var b=a.dataTransfer.getData("text");"pg_1_drop_"==a.currentTarget.id.substr(0,10)&&"pg_1_note_"==b.substr(0,10)&&move_interesse(document.getElementById(b),a.currentTarget.id)}
function drop_kategorie(a){a.preventDefault();var b=a.dataTransfer.getData("text");"pg_1_note_"==a.currentTarget.id.substr(0,10)&&"pg_1_drop_"==b.substr(0,10)&&move_interesse(a.currentTarget,b)}function allowDrop(a){a.preventDefault()}function dragStart(a){a.dataTransfer.setData("text",a.currentTarget.id);addClass(a.currentTarget,"dragged");null!=current_interesse&&(document.removeEventListener("click",current_interesse_handler),removeClass(current_interesse,"highlight"),current_interesse=null)}
function dragEnd(a){removeClass(a.currentTarget,"dragged")}
function click_interesse(a){null!=current_interesse&&(document.removeEventListener("click",current_interesse_handler),removeClass(current_interesse,"highlight"));current_interesse=a.currentTarget;addClass(current_interesse,"highlight");current_interesse_handler=function(a){a=a.target;do{if(a.id==current_interesse.id||"pg_1_drop_1"==a.id||"pg_1_drop_2"==a.id||"pg_1_drop_3"==a.id||"pg_1_drop_4"==a.id||"pg_1_drop_5"==a.id)return!0;a=a.parentNode}while(void 0!=a);removeClass(current_interesse,"highlight");
current_interesse=null;document.removeEventListener("click",current_interesse_handler)};document.addEventListener("click",current_interesse_handler)}
function click_kategorie(a){null==current_interesse?(addClass(a.currentTarget,"highlight"),showNote(a,a.currentTarget.id+"_detail","unused_bottom_note","unused_bottom_note",!0)):(move_interesse(current_interesse,a.currentTarget.id),document.removeEventListener("click",current_interesse_handler),removeClass(current_interesse,"highlight"),current_interesse=null)}
function move_interesse(a,b){var c=a.parentNode,f=document.getElementById(b+"_detail"),d=document.getElementById(b+"_counter"),e=parseInt(d.innerHTML)+1;0>=e||isNaN(e)?d.innerHTML="1":d.innerHTML=e;f.appendChild(a);a.style.zIndex=f.style.zIndex+1;"pg_1_drop_1_detail"==c.id||"pg_1_drop_2_detail"==c.id||"pg_1_drop_3_detail"==c.id||"pg_1_drop_4_detail"==c.id||"pg_1_drop_5_detail"==c.id?(d=document.getElementById(c.id.substr(0,11)+"_counter"),e=parseInt(d.innerHTML)-1,0>=e||isNaN(e)?d.innerHTML="":d.innerHTML=
e):(f=document.getElementById("progress_1"),counter-=2,f.style.width=counter/max_1*100+"%",document.getElementById("side_progress_text_1").innerHTML=counter+"",counter+=2,""==document.getElementById("pg_1_spawn_1").innerHTML&&""==document.getElementById("pg_1_spawn_2").innerHTML&&""==document.getElementById("pg_1_spawn_3").innerHTML?spawn_button_pg_1():spawn_interesse(c.id))}
function spawn_interesse(a){if(counter<max_1){var b=document.createElement("div");b.id="pg_1_note_"+counter;b.className="note inner_note slow text unused_right";b.draggable="true";var c=xml_daten.getElementsByTagName("interesse")[counter],f=document.createElement("div");f.className="info_button";f.appendChild(document.createTextNode("?"));b.appendChild(f);var d=document.createTextNode(c.getElementsByTagName("beschreibung")[0].innerHTML);b.appendChild(d);b.appendChild(document.createElement("br"));
d=document.createElement("div");d.id=b.id+"_cp_A";d.className="cp unused";d.appendChild(document.createTextNode(c.getElementsByTagName("cp_A")[0].innerHTML));b.appendChild(d);d=document.createElement("div");d.id=b.id+"_cp_W";d.className="cp unused";d.appendChild(document.createTextNode(c.getElementsByTagName("cp_W")[0].innerHTML));b.appendChild(d);d=document.createElement("div");d.id=b.id+"_cp_M";d.className="cp unused";d.appendChild(document.createTextNode(c.getElementsByTagName("cp_M")[0].innerHTML));
b.appendChild(d);b.appendChild(document.createElement("br"));d=document.createElement("div");d.id="pg_1_note_"+counter+"_help";d.className="note help text unused_right unused_all";var e=document.createElement("b");e.appendChild(document.createTextNode(c.getElementsByTagName("modul")[0].innerHTML));d.appendChild(e);e=document.createElement("ul");e.innerHTML=c.getElementsByTagName("info")[0].innerHTML;d.appendChild(e);d.style.zIndex=14;b.appendChild(d);document.getElementById(a).appendChild(b);b.addEventListener("dragstart",
dragStart);b.addEventListener("dragend",dragEnd);b.addEventListener("drop",drop_kategorie);b.addEventListener("dragover",allowDrop);b.addEventListener("click",click_interesse);var h="pg_1_note_"+counter+"_help";f.addEventListener("click",function(a){showNote(a,h,"unused_right","unused_right",!1)});setTimeout(function(){removeClass(b,"unused_right")},100);counter+=1}else counter++}
function spawn_button_pg_1(){addClass(document.getElementById("pg_1_text"),"unused_top");addClass(document.getElementById("pg_1_spawn_1"),"unused_all");addClass(document.getElementById("pg_1_spawn_2"),"unused_all");addClass(document.getElementById("pg_1_spawn_3"),"unused_all");var a=document.createElement("div");a.id="pg_1_button";a.className="button button_center heading unused_top";a.innerHTML="<p>Weiter</p>";document.getElementById("pg_1_upper_content").appendChild(a);a.addEventListener("click",
function(a){void 0!=a.currentTarget&&(wechsel_seite(2),setTimeout(spawn_aufgabe,700))});removeClass(document.getElementById("pg_1_continue_text"),"unused_all");setTimeout(function(){addClass(document.getElementById("pg_1_text"),"unused_all")},500);setTimeout(function(){removeClass(document.getElementById("pg_1_continue_text"),"unused_top")},600);setTimeout(function(){removeClass(a,"unused_top")},700)}
function roll_back(){counter-=2;document.getElementById("progress_2").style.width=counter/max_2*100+"%";document.getElementById("side_progress_text_3").innerHTML=counter+"";counter>=max_2-1?(removeClass(document.getElementById("pg_2_text"),"unused_all"),removeClass(document.getElementById("pg_2_task"),"unused_all"),removeClass(document.getElementById("pg_2_spawn_0"),"unused_all"),removeClass(document.getElementById("pg_2_spawn_1"),"unused_all"),removeClass(document.getElementById("pg_2_spawn_2"),
"unused_all"),removeClass(document.getElementById("pg_2_spawn_3"),"unused_all"),removeClass(document.getElementById("pg_2_text"),"unused_top"),addClass(document.getElementById("pg_2_button"),"unused_bottom"),addClass(document.getElementById("pg_2_continue_text"),"unused_top"),setTimeout(function(){document.getElementById("pg_2_upper_content").removeChild(document.getElementById("pg_2_button"));addClass(document.getElementById("pg_2_continue_text"),"unused_all");spawn_aufgabe()},500)):hide_aufgabe();
rolled_back=!0;setTimeout(function(){addClass(document.getElementById("pg_2_back"),"unused_right")},0);var a=document.getElementById("pg_2_answers"),b="pg_2_task_"+counter;for(i=a.childNodes.length-1;0<=i;i--)if(0===a.childNodes[i].id.lastIndexOf(b,0))return a.removeChild(a.childNodes[i]),!0;return!1}
function hide_aufgabe(){setTimeout(function(){addClass(document.getElementById("pg_2_task"),"unused_top")},0);setTimeout(function(){addClass(document.getElementById("pg_2_graphic"),"unused_right")},100);setTimeout(function(){addClass(document.getElementById("pg_2_spawn_0"),"unused_right")},200);setTimeout(function(){addClass(document.getElementById("pg_2_spawn_1"),"unused_right")},300);setTimeout(function(){addClass(document.getElementById("pg_2_spawn_2"),"unused_right")},400);setTimeout(function(){addClass(document.getElementById("pg_2_spawn_3"),
"unused_right")},500);setTimeout(clear_aufgabe,1E3)}function clear_aufgabe(){document.getElementById("pg_2_task").innerHTML="";document.getElementById("pg_2_graphic").innerHTML="";for(i=0;4>i;i++)document.getElementById("pg_2_spawn_"+i).innerHTML="";spawn_aufgabe()}
function spawn_aufgabe(){if(counter>=max_2)spawn_button_pg_2(),counter++;else{var a=xml_daten.getElementsByTagName("aufgabe")[counter];document.getElementById("pg_2_task").innerHTML=a.getElementsByTagName("beschreibung")[0].innerHTML;document.getElementById("pg_2_graphic").innerHTML=a.getElementsByTagName("grafik")[0].innerHTML;for(i=0;4>i;i++){var b=a.getElementsByTagName("antwort")[i];text=document.createTextNode(b.getElementsByTagName("beschreibung")[0].innerHTML);var c=document.createElement("div");
c.id="pg_2_task_"+counter+"_"+i;c.className="note inner_note text task";c.appendChild(text);c.appendChild(document.createElement("br"));var f=document.createElement("div");f.id=c.id+"_cp_A";f.className="cp unused";f.appendChild(document.createTextNode(b.getElementsByTagName("cp_A")[0].innerHTML));c.appendChild(f);f=document.createElement("div");f.id=c.id+"_cp_W";f.className="cp unused";f.appendChild(document.createTextNode(b.getElementsByTagName("cp_W")[0].innerHTML));c.appendChild(f);f=document.createElement("div");
f.id=c.id+"_cp_M";f.className="cp unused";f.appendChild(document.createTextNode(b.getElementsByTagName("cp_M")[0].innerHTML));c.appendChild(f);document.getElementById("pg_2_spawn_"+i).appendChild(c);var d=function(a){if(void 0!=a.currentTarget){var b=a.currentTarget;addClass(b,"highlight");setTimeout(function(){document.getElementById("pg_2_answers").appendChild(document.getElementById(b.id));document.getElementById(b.id).removeEventListener("click",d);document.getElementById("progress_2").style.width=
counter/max_2*100+"%";document.getElementById("side_progress_text_3").innerHTML=counter+"";rolled_back&&(setTimeout(function(){removeClass(document.getElementById("pg_2_back"),"unused_right")},1100),rolled_back=!1);hide_aufgabe()},200)}};c.addEventListener("click",d)}setTimeout(function(){removeClass(document.getElementById("pg_2_task"),"unused_top")},100);setTimeout(function(){removeClass(document.getElementById("pg_2_graphic"),"unused_right")},200);setTimeout(function(){removeClass(document.getElementById("pg_2_spawn_0"),
"unused_right")},300);setTimeout(function(){removeClass(document.getElementById("pg_2_spawn_1"),"unused_right")},400);setTimeout(function(){removeClass(document.getElementById("pg_2_spawn_2"),"unused_right")},500);setTimeout(function(){removeClass(document.getElementById("pg_2_spawn_3"),"unused_right")},600);counter+=1}}
function spawn_button_pg_2(){addClass(document.getElementById("pg_2_text"),"unused_top");addClass(document.getElementById("pg_2_task"),"unused_top");addClass(document.getElementById("pg_2_spawn_0"),"unused_all");addClass(document.getElementById("pg_2_spawn_1"),"unused_all");addClass(document.getElementById("pg_2_spawn_2"),"unused_all");addClass(document.getElementById("pg_2_spawn_3"),"unused_all");var a=document.createElement("div");a.id="pg_2_button";a.className="button button_center heading unused_top";
a.innerHTML="<p>Weiter</p>";document.getElementById("pg_2_upper_content").appendChild(a);a.addEventListener("click",function(a){void 0!=a.currentTarget&&(wechsel_seite(3),spawn_auswertung())});removeClass(document.getElementById("pg_2_continue_text"),"unused_all");setTimeout(function(){addClass(document.getElementById("pg_2_text"),"unused_all");addClass(document.getElementById("pg_2_task"),"unused_all")},500);setTimeout(function(){removeClass(document.getElementById("pg_2_continue_text"),"unused_top")},
600);setTimeout(function(){removeClass(a,"unused_top")},700)}
function spawn_auswertung(){for(var a=xml_daten.getElementsByTagName("auswertung")[0],b=[0,0,0],c=[0,0,0],f=1,d,e=1;6>e;e++){var h=document.getElementById("pg_1_drop_"+e+"_detail");d=0;for(var g=h.childNodes[d];void 0!=g;){var k=parseFloat(document.getElementById(g.id+"_cp_A").innerHTML),m=parseFloat(document.getElementById(g.id+"_cp_W").innerHTML),g=parseFloat(document.getElementById(g.id+"_cp_M").innerHTML);b[0]+=k;b[1]+=m;b[2]+=g;c[0]+=k*f;c[1]+=m*f;c[2]+=g*f;g=h.childNodes[++d]}f-=.25}e=[c[0]*
c[0],c[1]*c[1],c[2]*c[2]];h=d=0;if(0==e[0]&&0==e[1]&&0==e[2])d=250,h=318.67;else{h=e[0]+e[1]+e[2];for(d=0;3>d;d++)e[d]/=h;d=(2*e[1]+e[0])/2;h=.8660254038*e[0];d*=500;h=463.01-500*h}e=document.createElementNS("http://www.w3.org/2000/svg","circle");e.setAttributeNS(null,"cx",d);e.setAttributeNS(null,"cy",h);e.setAttributeNS(null,"r",5);e.setAttributeNS(null,"fill","black");document.getElementById("pg_3_svg").appendChild(e);f=[parseFloat(a.getElementsByTagName("cp_A_min")[0].innerHTML)*b[0],parseFloat(a.getElementsByTagName("cp_W_min")[0].innerHTML)*
b[1],parseFloat(a.getElementsByTagName("cp_M_min")[0].innerHTML)*b[2]];k="";m=!1;c[0]>f[0]&&c[1]>f[1]&&c[2]>f[2]?k=a.getElementsByTagName("AWM")[0].innerHTML:c[0]>f[0]&&c[1]>f[1]?k=a.getElementsByTagName("AW")[0].innerHTML:c[0]>f[0]&&c[2]>f[2]?k=a.getElementsByTagName("AM")[0].innerHTML:c[0]>f[0]?k=a.getElementsByTagName("A")[0].innerHTML:c[1]>f[1]&&c[2]>f[2]?k=a.getElementsByTagName("WM")[0].innerHTML:c[1]>f[1]?k=a.getElementsByTagName("W")[0].innerHTML:c[2]>f[2]?k=a.getElementsByTagName("M")[0].innerHTML:
(m=!0,k=a.getElementsByTagName("keine")[0].innerHTML);h=document.getElementById("pg_2_answers");d=0;for(g=h.childNodes[0];void 0!=g;)c[0]+=parseFloat(document.getElementById(g.id+"_cp_A").innerHTML),c[1]+=parseFloat(document.getElementById(g.id+"_cp_W").innerHTML),c[2]+=parseFloat(document.getElementById(g.id+"_cp_M").innerHTML),g=h.childNodes[++d];h=xml_daten.getElementsByTagName("aufgabe");for(d=0;d<h.length;d++){for(var g=h[d].getElementsByTagName("cp_A"),e=0;e<g.length;e++){var l=parseFloat(g[e].innerHTML);
0<l&&(b[0]+=l)}g=h[d].getElementsByTagName("cp_W");for(e=0;e<g.length;e++)l=parseFloat(g[e].innerHTML),0<l&&(b[1]+=l);g=h[d].getElementsByTagName("cp_M");for(e=0;e<g.length;e++)l=parseFloat(g[e].innerHTML),0<l&&(b[2]+=l)}d=[parseFloat(a.getElementsByTagName("cp_A_max")[0].innerHTML)*b[0],parseFloat(a.getElementsByTagName("cp_W_max")[0].innerHTML)*b[1],parseFloat(a.getElementsByTagName("cp_M_max")[0].innerHTML)*b[2]];c[0]>d[0]||c[1]>d[1]||c[2]>d[2]?k=a.getElementsByTagName("gut")[0].innerHTML+k:m||
(k=a.getElementsByTagName("mid")[0].innerHTML+k);document.getElementById("pg_3_auswertung").innerHTML=k;for(d=0;3>d;d++)b[d]-=f[d],c[d]-=f[d],c[d]=0>c[d]?0:c[d];a=Math.max(c[0]/b[0],c[1]/b[1],c[2]/b[2]);a=500*a-2.5;e=document.createElementNS("http://www.w3.org/2000/svg","rect");e.setAttributeNS(null,"x",a);e.setAttributeNS(null,"y",510);e.setAttributeNS(null,"rx",2.5);e.setAttributeNS(null,"ry",2.5);e.setAttributeNS(null,"height",40);e.setAttributeNS(null,"width",5);e.setAttributeNS(null,"fill","black");
document.getElementById("pg_3_svg").appendChild(e);setTimeout(function(){removeClass(document.getElementById("pg_3_auswertung"),"unused_top")},800);setTimeout(function(){removeClass(document.getElementById("pg_3_print"),"unused_top")},900);setTimeout(function(){removeClass(document.getElementById("pg_3_svg_outer"),"unused_top")},1E3)};